// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4rLGOHg4DBjZayIL-Z14w9caHh-DoLEQ',
    appId: '1:48691033386:web:3a0ad408fd112f7c215a53',
    messagingSenderId: '48691033386',
    projectId: 'my-todo-2b072',
    authDomain: 'my-todo-2b072.firebaseapp.com',
    storageBucket: 'my-todo-2b072.appspot.com',
    measurementId: 'G-DFCMDEYT40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn8zwzaYEY4Dhc_NtlwXUOW_LMyKDrX6o',
    appId: '1:48691033386:android:f7ce2e2371665340215a53',
    messagingSenderId: '48691033386',
    projectId: 'my-todo-2b072',
    storageBucket: 'my-todo-2b072.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyZFqW7Qwx3y_NGj9IrJnRZh0xxZ_Ehfw',
    appId: '1:48691033386:ios:506efe9496b56555215a53',
    messagingSenderId: '48691033386',
    projectId: 'my-todo-2b072',
    storageBucket: 'my-todo-2b072.appspot.com',
    iosClientId: '48691033386-hufkki71j2jvbj2lsq5nvv6p4buiomn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.madd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyZFqW7Qwx3y_NGj9IrJnRZh0xxZ_Ehfw',
    appId: '1:48691033386:ios:66b3bbda7c3214af215a53',
    messagingSenderId: '48691033386',
    projectId: 'my-todo-2b072',
    storageBucket: 'my-todo-2b072.appspot.com',
    iosClientId: '48691033386-h7hnh5ocgf3c0aba6ugdn6csb82ptpn5.apps.googleusercontent.com',
    iosBundleId: 'com.example.madd.RunnerTests',
  );
}
